### ISSUE TITLE
Spark Packages Release

### ISSUE THREAD

**Issue by brkyvz** [FlytxtRnD/GMM#1]
Hi,
Would you like to make a release to the Spark Packages Repository with this nice library? This will allow users to run your package with ease, simply by adding the flag:
`--packages FlytxtRnD/GMM:0.1` to pyspark or spark-submit.

Your package will also be ranked higher on the website for having a distribution.
You may use the [spark-package command tool](https://github.com/databricks/spark-package-cmd-tool) to make a release directly from the command line!

Let me know if you have any difficulties in making this happen!

Best,
Burak

**Comment by FlytxtRnD** [comment]
@brkyvz 
We are not able to publish the package.Please review the following steps and help to solve the issue
1. Created a new folder in my local system named packages
2. Move to the packages folder
3. spark-package init -p -n FlytxtRnD/GMM
4. spark-package zip -f GMM -n FlytxtRnD/GMM -v 0.1
4. spark-package publish -c credentials -z GMM-0.1.zip -n "FlytxtRnD/GMM" -v "0.1"

Last statement shows an error "please specify the folder of the package".Could you please tell where we need to give the github repository URL?

**Comment by brkyvz** [comment]
@FlytxtRnD Thanks for letting me know. I'll fix it.
Can you please simply try the following command:
`spark-package publish -c credentials -f GMM -z GMM-0.1.zip -n "FlytxtRnD/GMM" -v "0.1"`
The github repository url we can derive from the package name, so you don't need to enter it. On thing that you should be careful about is that, we automatically read the "git commit sha" from your local repository (the folder) That's why we still need your folder. I should update the README.

Please make sure that the commit is also pushed to your remote repository.

Thanks,
Burak

**Comment by FlytxtRnD** [comment]
Done. Thanks @brkyvz for your help.
